Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,7 +35,6 @@ jobs:
 
     - name: Get AKS and ACR info
       run: |
-        docker build -t gtazurecontainerregistry.azurecr.io/your-app-name:2dcb49edc5d2d5c19d62d55443c21736fb26d01d -f Dockerfile .
         AKS_NAME=$(az aks list --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query "[0].name" -o tsv)
         ACR_NAME=$(az acr list --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query "[0].name" -o tsv)
         echo "AKS_CLUSTER_NAME=$AKS_NAME" >> $GITHUB_ENV
@@ -58,6 +57,18 @@ jobs:
         login-server: ${{ env.ACR_NAME }}.azurecr.io
         username: ${{ secrets.AZURE_CLIENT_ID }}
         password: ${{ secrets.AZURE_CLIENT_SECRET }}
+
+    - name: Get ACR info
+      run: |
+          echo "Fetching ACR info..."
+          ACR_NAME=$(az acr list --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query "[0].name" -o tsv)
+          if [ -z "$ACR_NAME" ]; then
+          echo "Error: Failed to fetch ACR name. Make sure the resource group exists and contains an Azure Container Registry."
+           exit 1
+           fi
+           echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
+           echo "ACR name set to: $ACR_NAME
+        
     - run: |
         docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} -f ${{ env.DOCKER_FILE_PATH }} .
         docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
